### PR TITLE
Update to README.md

### PR DESCRIPTION
**Pull request by Boldfor**
Stumbled upon the really nice BS440 project and this BS440-HA-AD-extension (thanks for the effort btw). Will aim at fixing this bug https://github.com/keptenkurk/BS440/issues/102 (which I have as well / can safely reproduce) but will start with updating some of the documentation first.

### CODE REVIEW

**Review by creatvty — APPROVED** [review]
Hey, thanks for the effort. I can't confirm all of these findings myself but I like it and I'm sure you did your homework :wink:

**Comment by Boldfor** [comment]
Yeah, we'll, ehm, thanks. I mean, I don't want to ruin the party, but this was _literally_ my first PR on GitHub (like, ehm, _ever_), and I only started with python like five days ago (with the official tutorial). ;)

So if you trust in me, that's very nice to hear, but maybe, if you have some time, do a reinstall on your end and do a test as well Of course I tested it on my end as well (and everything works), and the changes were very very minor, but just to be sure. ;)

Update: This relates of course more to my PR2 which fixed three minor bugs.

**Comment by creatvty** [comment]
Haha don't worry about it. It''s not like this is the most import project ever. Not sure if anybody apart from me and you actually already used this particular fork.

Keep at it. I think this looks already quite good.

**Comment by Boldfor** [comment]
> Haha don't worry about it. It''s not like this is the most import project ever. Not sure if anybody apart from me and you actually already used this particular fork.

Haha, I listened to a podcast with Guido van Rossum, and he was asked what he'd recommend to start learning python. He said "pick a problem which you'd like to solve". And on that weekend we bought the new scale, and I stumbled upon this project.

Anyway, maybe a dumb question: Why isn't your fork merged back to the keptenturk-master? This would make sense, since no progress has happened ever since, and then there's only one main version out there?

**Comment by creatvty** [comment]
Niice! That's it!
I actually didn't think of it really. It didn't really seem like it was still maintained. But I can make a PR and we can see

**Comment by Boldfor** [comment]
Also not sure either. But the fact that all the issues are there, and it's where it startet, it could be worth a try.

**Comment by creatvty** [comment]
[Done](https://github.com/keptenkurk/BS440/pull/104) let's see

**Comment by Boldfor** [comment]
Thanks. A bit curious what will happen now.

Out of curiosity (I'm using this script also to learn new things): Do you know what it would take to create a docker out of this git? I know, completely over the top (also given the popularity of it), but I'm running a smart home system at my place and can set up the entire system with just one docker-compose.yml (incl. other rather complex stuff like [wmbusmeters](https://github.com/weetmuts/wmbusmeters), but BS440 is the only component that requires a long list of manual steps to be done. Would be nice to set up BS440 like any other container via docker.

You have experience with this stuff, or have knowledge of a good reference on how the script could be brought there?

**Comment by Boldfor** [comment]
> [Done](https://github.com/keptenkurk/BS440/pull/104) let's see

Great, it worked. Thanks!

**Comment by creatvty** [comment]
> Thanks. A bit curious what will happen now.
> 
> Out of curiosity (I'm using this script also to learn new things): Do you know what it would take to create a docker out of this git? I know, completely over the top (also given the popularity of it), but I'm running a smart home system at my place and can set up the entire system with just one docker-compose.yml (incl. other rather complex stuff like [wmbusmeters](https://github.com/weetmuts/wmbusmeters), but BS440 is the only component that requires a long list of manual steps to be done. Would be nice to set up BS440 like any other container via docker.
> 
> You have experience with this stuff, or have knowledge of a good reference on how the script could be brought there?

Sorry, forgot to answer this. Most aspects of this should be pretty simple. The only thing of course is getting access to the Bluetooth interface. I'm not sure how easy that is.
I have some experience with Docker although I'm working mostly with JS / Node.

**Comment by Boldfor** [comment]
> Most aspects of this should be pretty simple. The only thing of course is getting access to the Bluetooth interface. I'm not sure how easy that is. I have some experience with Docker although I'm working mostly with JS / Node.
Yep, there are some aspects (mostly Bluetooth probably) that could be tricky.

Anyway, I created an item (https://github.com/keptenkurk/BS440/issues/106, mostly for myself). Maybe I'll find some time digging into this. If you know something, feel free to contribute.

**Pull request merged**
